display_name: Avalon

packager: MasterAlanLab
packagerEmail: masteralanlab@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/desktop_icon.png

requires:
  - libsecret

keywords:
  - Avalon
  - Clash
  - ClashMeta
  - Proxy

generic_name: Avalon

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/avalon
  - x-scheme-handler/vless
  - x-scheme-handler/vmess
  - x-scheme-handler/ss
  - x-scheme-handler/trojan
  - x-scheme-handler/hysteria2
  - x-scheme-handler/hy2
  - x-scheme-handler/tuic
  - x-scheme-handler/anytls
  - x-scheme-handler/socks
  - x-scheme-handler/socks5
  - x-scheme-handler/socks4
  - x-scheme-handler/socks4a

group: Applications/Internet

startup_notify: true
